feat: header
gcba/Obelisco-V2 pull request #74
Opened 2024-09-13 18:32 UTC by victorianastasi

2024-09-19 19:43 UTC, davisLjr requested changes

2024-09-19 19:43 UTC, davisLjr commented on src/styles/components/_header.scss
![image](https://github.com/user-attachments/assets/c66b5a35-8b0d-4302-b698-11e22e3c1546)

Homelo chino dice que puede que te falte un z-index en el desplegable.

![image](https://github.com/user-attachments/assets/3d7e354d-3587-4e90-a9b3-e19d68bedd54)

![image](https://github.com/user-attachments/assets/d1803455-754a-4e64-8531-96d464e8ef0c)

2024-09-19 19:46 UTC, davisLjr commented on src/styles/components/_header.scss
![image](https://github.com/user-attachments/assets/df2608fd-6715-4ad0-bc3f-11b869aa0043)


Ahi adjunto otra prueba colocando el header por fuera del code box 

![image](https://github.com/user-attachments/assets/2689da69-724a-4075-ad62-b23b064a94c6)

2024-09-20 13:22 UTC, victorianastasi commented on src/styles/components/_header.scss
Lo estoy probando, y lo veo asi:
![image](https://github.com/user-attachments/assets/40f96bb5-0178-489e-afb3-0e2ab15c3ee2)
--
![image](https://github.com/user-attachments/assets/a23a1691-11f1-4c1f-b22d-eceb415bf0d6)

En layout lo coloque asi:
![image](https://github.com/user-attachments/assets/b3816aac-3490-423d-ba4a-6cfb5c4d7f45)

Lo colocaste asi tambien? o con el contenedor de header-box-sizing?

2024-09-24 17:22 UTC, davisLjr approved these changes

2024-09-24 17:34 UTC, merged